force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Points</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeagueTableServiceTest.cls
@isTest
private class LeagueTableServiceTest {
  private class FakeTeamRepository implements ITeamRepository {
    public List<Team__c> getLeagueTableTeams() {
      return new List<Team__c>{
        new Team__c(Name = 'A', Points__c = 1),
        new Team__c(Name = 'B', Points__c = 2)
      };
    }
  }

  @isTest
  static void testGetLeagueTable() {
    FakeTeamRepository repo = new FakeTeamRepository();
    LeagueTableService leagueTableService = new LeagueTableService(repo);
    List<Team__c> teams = leagueTableService.getLeagueTable();
    System.assertEquals(2, teams.size());
    System.assertEquals('A', teams[0].Name);
    System.assertEquals('B', teams[1].Name);
  }
}