force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <label>Match</label>
    <nameField>
        <label>Match Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Away_Goals__c.field-meta.xml
<CustomField>
    <fullName>Away_Goals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Away_Goals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Away_Team__c.field-meta.xml
<CustomField>
    <fullName>Away_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Away_Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches (Away_Team)</relationshipLabel>
    <relationshipName>Matches1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Goal__c.field-meta.xml
<CustomField>
    <fullName>Home_Goal__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Home_Goals</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Home_Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Matches</relationshipLabel>
    <relationshipName>Matches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Played</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Points</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MatchTriggerTest.cls
@isTest
private class MatchTriggerTest {
  @isTest
  static void testMatchTrigger_InsertAsPlayed() {
    Team__c team1 = new Team__c();
    team1.Name = '1';
    team1.Points__c = 0;

    Team__c team2 = new Team__c();
    team2.Name = '2';
    team2.Points__c = 0;

    List<Team__c> tempTeams = new List<Team__c>{ team1, team2 };

    insert tempTeams;

    List<Id> teamsIds = new List<Id>{ team1.Id, team2.Id };

    Match__c newMatch = new Match__c();
    newMatch.Home_Team__c = team1.Id;
    newMatch.Away_Team__c = team2.Id;
    newMatch.Home_Goal__c = 1;
    newMatch.Away_Goals__c = 2;
    newMatch.Status__c = 'Played';
    newMatch.Match_Date__c = Date.today();

    List<Match__c> newMatches = new List<Match__c>();
    newMatches.add(newMatch);

    Test.startTest();
    insert newMatches;
    Test.stopTest();

    List<Team__c> updatedTeams = [
      SELECT ID, Points__c
      FROM Team__c
      WHERE ID IN :teamsIds
    ];

    for (Team__c t : updatedTeams) {
      if (t.Id == team1.Id) {
        System.assertEquals(0, t.Points__c);
      } else if (t.Id == team2.Id) {
        System.assertEquals(3, t.Points__c);
      }
    }
  }

  @isTest
  static void testMatchTrigger_StatusChangeToPlayed() {
    Team__c team1 = new Team__c();
    team1.Name = '1';
    team1.Points__c = 0;

    Team__c team2 = new Team__c();
    team2.Name = '2';
    team2.Points__c = 0;

    List<Team__c> teams = new List<Team__c>{ team1, team2 };

    insert teams;

    Set<Id> teamsId = new Set<Id>{ team1.Id, team2.Id };

    Match__c newMatch = new Match__c();
    newMatch.Home_Team__c = team1.Id;
    newMatch.Away_Team__c = team2.Id;
    newMatch.Home_Goal__c = 2;
    newMatch.Away_Goals__c = 2;
    newMatch.Status__c = 'Scheduled';

    insert newMatch;

    List<Match__c> insertedMatch = [
      SELECT ID, Status__c
      FROM Match__c
      WHERE ID = :newMatch.Id
    ];

    insertedMatch[0].Status__c = 'Played';

    Test.startTest();
    update insertedMatch;
    Test.stopTest();

    List<Team__c> updatedTeams = [
      SELECT ID, Points__c
      FROM Team__c
      WHERE ID IN :teamsId
    ];

    for (Team__c t : updatedTeams) {
      if (t.Id == team1.Id) {
        System.assertEquals(1, t.Points__c);
      } else if (t.Id == team2.Id) {
        System.assertEquals(1, t.Points__c);
      }
    }
  }

  @isTest
  static void testMatchTrigger_DeleteMatch() {
    Team__c team1 = new Team__c();
    team1.Name = '1';
    team1.Points__c = 0;

    Team__c team2 = new Team__c();
    team2.Name = '2';
    team2.Points__c = 0;

    List<Team__c> teams = new List<Team__c>{ team1, team2 };

    insert teams;

    Set<Id> teamsId = new Set<Id>{ team1.Id, team2.Id };

    Match__c newMatch = new Match__c();
    newMatch.Home_Team__c = team1.Id;
    newMatch.Away_Team__c = team2.Id;
    newMatch.Home_Goal__c = 2;
    newMatch.Away_Goals__c = 2;
    newMatch.Status__c = 'Played';

    List<Match__c> newMatches = new List<Match__c>();
    newMatches.add(newMatch);

    insert newMatches;

    Test.startTest();
    delete newMatches;
    Test.stopTest();

    List<Team__c> updatedTeams = [
      SELECT ID, Points__c
      FROM Team__c
      WHERE ID IN :teamsId
    ];

    for (Team__c t : updatedTeams) {
      if (t.Id == team1.Id) {
        System.assertEquals(0, t.Points__c);
      } else if (t.Id == team2.Id) {
        System.assertEquals(0, t.Points__c);
      }
    }
  }

  @isTest
  static void testMatchTrigger_StatusChangeBackToScheduled() {
    Team__c team1 = new Team__c();
    team1.Name = '1';
    team1.Points__c = 0;

    Team__c team2 = new Team__c();
    team2.Name = '2';
    team2.Points__c = 0;

    List<Team__c> teams = new List<Team__c>{ team1, team2 };

    insert teams;

    Set<Id> teamsId = new Set<Id>{ team1.Id, team2.Id };

    Match__c newMatch = new Match__c();
    newMatch.Home_Team__c = team1.Id;
    newMatch.Away_Team__c = team2.Id;
    newMatch.Home_Goal__c = 2;
    newMatch.Away_Goals__c = 2;
    newMatch.Status__c = 'Played';

    insert newMatch;

    teams = [
      SELECT ID, Points__c
      FROM Team__c
      WHERE ID IN :teamsId
    ];

    for (Team__c t : teams) {
      if (t.Id == team1.Id) {
        System.assertEquals(1, t.Points__c);
      } else if (t.Id == team2.Id) {
        System.assertEquals(1, t.Points__c);
      }
    }

    List<Match__c> insertedMatch = [
      SELECT ID, Status__c
      FROM Match__c
      WHERE ID = :newMatch.Id
    ];

    insertedMatch[0].Status__c = 'Scheduled';

    Test.startTest();
    update insertedMatch;
    Test.stopTest();

    List<Team__c> updatedTeams = [
      SELECT ID, Points__c
      FROM Team__c
      WHERE ID IN :teamsId
    ];

    for (Team__c t : updatedTeams) {
      if (t.Id == team1.Id) {
        System.assertEquals(0, t.Points__c);
      } else if (t.Id == team2.Id) {
        System.assertEquals(0, t.Points__c);
      }
    }
  }

  @isTest
  static void testMatchTrigger_ChangeScoreWhilePlayed() {
    Team__c team1 = new Team__c();
    team1.Name = '1';
    team1.Points__c = 0;

    Team__c team2 = new Team__c();
    team2.Name = '2';
    team2.Points__c = 0;

    List<Team__c> teams = new List<Team__c>{ team1, team2 };

    insert teams;

    Set<Id> teamsId = new Set<Id>{ team1.Id, team2.Id };

    Match__c newMatch = new Match__c();
    newMatch.Home_Team__c = team1.Id;
    newMatch.Away_Team__c = team2.Id;
    newMatch.Home_Goal__c = 1;
    newMatch.Away_Goals__c = 0;
    newMatch.Status__c = 'Played';

    List<Match__c> newMatches = new List<Match__c>();
    newMatches.add(newMatch);

    insert newMatches;

    teams = [
      SELECT ID, Points__c
      FROM Team__c
      WHERE ID IN :teamsId
    ];

    for (Team__c t : teams) {
      if (t.Id == team1.Id) {
        System.assertEquals(3, t.Points__c);
      } else if (t.Id == team2.Id) {
        System.assertEquals(0, t.Points__c);
      }
    }

    newMatch.Home_Goal__c = 2;
    newMatch.Away_Goals__c = 2;
    newMatch.Status__c = 'Played';

    update newMatches;

    teams = [
      SELECT ID, Points__c
      FROM Team__c
      WHERE ID IN :teamsId
    ];

    for (Team__c t : teams) {
      if (t.Id == team1.Id) {
        System.assertEquals(1, t.Points__c);
      } else if (t.Id == team2.Id) {
        System.assertEquals(1, t.Points__c);
      }
    }
  }
}